# docker-compose.yml 
version: '3'
 
services:
  portainer:
    image: portainer/portainer-ce:2.18.4-alpine
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - /portainer-data:/data
    ports:
      - 9000:9000
      - 8000:8000